spring:
  datasource:
    db1:
      url: jdbc:mysql://localhost:3306/spb1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver

    db2:
      url: jdbc:mysql://localhost:3306/spb2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver

    db3:
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: SPB_001
      password: 123456
      driverClassName: oracle.jdbc.driver.OracleDriver

logging:
  level:
    com:
      shenjinxiang:
        spb:
          mapper: debug
